### ISSUE TITLE
Error while installing Cost Spread on Odoo 11 EE

### ISSUE THREAD

**Issue by wshamasneh** [onesteinbv/addons-onestein#68]
Error raised up while installing Cost Spread (account_cost_spread) on Odoo 11 CE with sample data.

the error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 1036, in _validate_fields
    check(self)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 335, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 1054, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 509, in raise_view_error
    raise ValueError(message)
ValueError: Field `spread_journal_id` does not exist

Error context:
View `account.invoice.line form`
[view_id: 542, xml_id: n/a, model: account.invoice.line, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_model.py", line 1487, in _update
    record = record.create(values)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3380, in create
    self._fields[key].determine_inverse(record)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3089, in write
    self._write(old_vals)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3255, in _write
    self._validate_fields(vals)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nField `spread_journal_id` does not exist\n\nError context:\nView `account.invoice.line form`\n[view_id: 542, xml_id: n/a, model: account.invoice.line, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 751, in parse
    exc_info[2]
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_model.py", line 1487, in _update
    record = record.create(values)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3380, in create
    self._fields[key].determine_inverse(record)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3089, in write
    self._write(old_vals)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3255, in _write
    self._validate_fields(vals)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field `spread_journal_id` does not exist

Error context:
View `account.invoice.line form`
[view_id: 542, xml_id: n/a, model: account.invoice.line, parent_id: n/a]
None" while parsing file:/d:/program%20files%20(x86)/odoo%2011.0/server/odoo/addons/account_cost_spread/views/account_invoice_line.xml:4, near
<record id="view_invoice_line_spread" model="ir.ui.view">
        <field name="model">account.invoice.line</field>
        <field name="arch" type="xml">
            <form class="o_account_cost_spread">
                <header>
                    <button name="action_recalculate_spread" type="object" string="Recalculate entire spread" class="oe_highlight" attrs="{'invisible': [('spread_account_id', '=', False)]}"/>
                    <button name="action_undo_spread" type="object" string="Undo spread" attrs="{'invisible': [('spread_line_ids', '=', [])]}"/>
                </header>
                <sheet>
                    <group name="main_info">
                        <group>
                            <field name="account_id" readonly="1"/>
                            <field name="name" readonly="1"/>
                            <field name="price_subtotal" readonly="1"/>
                            <field name="remaining_amount" attrs="{'invisible': [('remaining_amount', '=', 0)]}" class="oe_form_invalid"/>
                        </group>
                        <group>
                            <field name="company_id" invisible="1"/>
                            <field name="spread_account_id" required="1" domain="[('company_id', '=', company_id)]"/>
                            <field name="period_number" required="1"/>
                            <field name="period_type" required="1"/>
                            <field name="spread_date"/>
                            <field name="spread_journal_id"/>
                            <field name="spread_move_line_auto_post"/>
                        </group>
                    </group>
                    <group name="extension">
                        <group name="extension_left">
                        </group>
                        <group name="extension_right">
                        </group>
                    </group>
                    <field name="spread_line_ids" readonly="1">
                        <tree>
                            <field name="name" readonly="1"/>
                            <field name="amount" readonly="1" sum="Total"/>
                            <field name="line_date" readonly="1"/>
                            <field name="move_id" readonly="1"/>
                            <button name="create_move" icon="fa fa-play" string="Create Move" type="object" attrs="{'invisible':[('move_id','!=',False)]}"/>
                            <button name="open_move" icon="fa fa-plus-square-o" string="View Move" type="object" attrs="{'invisible':[('move_id','=',False)]}"/>
                            <button name="unlink_move" icon="fa fa-times" string="Delete Move" type="object" confirm="This will delete the move. Are you sure ?" groups="account.group_account_manager" attrs="{'invisible':[('move_id','=',False)]}"/>
                        </tree>
                    </field>
                </sheet>
            </form>
        </field>
    </record>

**Comment by wshamasneh** [comment]
This issue now is resolved.
