### ISSUE TITLE
bi_view_editor :  error when opening view editor on new view

### ISSUE THREAD

**Issue by Moret84** [onesteinbv/addons-onestein#7]
Hi, 
I have a bug when I want to create a new custom BI views.
Steps to reproduce : 
Custom BI Views > Create > Input  random name and select nothing in query list> Save > Generate BI View give the following output:

```
Traceback (most recent call last):
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-80/base/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/it-traceurdirect/aoe-80/base/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/it-traceurdirect/aoe-80/base/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-80/base/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-80/base/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-80/addons-partners/bi_view_editor/models/bve_view.py", line 220, in action_create
    _build_query()
  File "/home/it-traceurdirect/aoe-80/addons-partners/bi_view_editor/models/bve_view.py", line 124, in _build_query
    info = _get_fields_info(json.loads(self.data))
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

Probably because of the empty query.

Also, when I create a view the same way but putting some query in the field, then save and generate Bi view, I can't open BI view i get the following message:

```
Traceback (most recent call last):
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-80/base/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/it-traceurdirect/aoe-80/base/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/it-traceurdirect/aoe-80/base/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'fields_view_get'
```

**Comment by astirpe** [comment]
Hi @Moret84 
I updated the code, could you try whether the error still occurs?

**Comment by mamaf** [comment]
I have the same error, with your updated code
I create a view, generate a BI view
And when I want to use it (Open BI view)

Traceback (most recent call last):
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/it-traceurdirect/aoe-80/base/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/it-traceurdirect/aoe-80/base/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/it-traceurdirect/aoe-80/base/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/it-traceurdirect/aoe-80/base/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
AttributeError: 'NoneType' object has no attribute 'fields_view_get'

**Comment by astirpe** [comment]
Hi, since my previous comment I was never able to reproduce this error.

If you can reproduce the error, please create an issue in [reporting-engine issues](https://github.com/OCA/reporting-engine/issues).
Thanks!

**Comment by mamaf** [comment]
Sorry but I can't see the module anymore in your repositories to get the last version ...

**Comment by astirpe** [comment]
The bi_view_editor V8 is hosted in [OCA/reporting-engine/tree/8.0](https://github.com/OCA/reporting-engine/tree/8.0).
The bi_view_editor V9 is not yet merged in OCA and you can find the latest version in [onesteinbv/addons-onestein/tree/9.0](https://github.com/onesteinbv/addons-onestein/tree/9.0).
Any feedback would be appreciated!

**Comment by mamaf** [comment]
I can't reproduce in a simple environment, but I still get this error on an existing customer environment :

Traceback (most recent call last):
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/home/it-traceurdirect/aoe-dev_80/base/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/it-traceurdirect/aoe-dev_80/base/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-dev_80/addons-tmp/bi_view_editor/models/bve_view.py", line 221, in action_create
    obj = _build_object()
  File "/home/it-traceurdirect/aoe-dev_80/addons-tmp/bi_view_editor/models/bve_view.py", line 175, in _build_object
    res_id = self.env['ir.model'].sudo().create(_prepare_object())
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/it-traceurdirect/aoe-dev_80/addons-tmp/bi_view_editor/models/ir_model.py", line 146, in create
    res = super(ir_model,self).create(cr, user, vals, context)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/addons/base/ir/ir_model.py", line 222, in create
    model._auto_init(cr, ctx)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/models.py", line 2554, in _auto_init
    cr.execute('ALTER TABLE "%s" ADD COLUMN "%s" %s' % (self._table, k, c[2]))
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/it-traceurdirect/aoe-dev_80/base/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: ERREUR:  « x_bve_ventes3 » n'est ni une table, ni un type composite, ni une table distante

**Comment by astirpe** [comment]
You should try to uninstall and reinstall the module again. Contact me in private if you prefer.

**Comment by mamaf** [comment]
That's what I did
Don't have your email address
