### ISSUE TITLE
Programming error: column t0.write_uid does not exist

### ISSUE THREAD

**Issue by aldebarande-fr** [onesteinbv/addons-onestein#9]
Hello,

each time i try to create a new bi view with a custom module i have this error : 
2016-03-31 09:53:34,675 2917 ERROR penibility openerp.sql_db: Programming error: column t0.write_uid does not exist
LINE 2:                 SELECT t0.id AS id,t0.write_uid AS write_uid...
                                           ^
, in query CREATE or REPLACE VIEW x_bve_test as (
                SELECT t0.id AS id,t0.write_uid AS write_uid,t0.write_date AS write_date,t0.create_uid AS create_uid,t0.create_date AS create_date,t0.geh_id AS x_geh_id
                FROM  alde_bilan_geh AS t0
                WHERE TRUE
                )
2016-03-31 09:53:34,675 2917 ERROR penibility openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo8.0-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo8.0-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo8.0-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo8.0-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo8.0-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo8.0-server/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo8.0-server/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo8.0-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo8.0-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo8.0-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo8.0-server/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/custom/odoo8.0/art_risque/bi_view_editor/models/bve_view.py", line 255, in action_create
    _build_query()
  File "/opt/odoo/custom/odoo8.0/art_risque/bi_view_editor/models/bve_view.py", line 172, in _build_query
    self.env.cr.execute(q)
  File "/opt/odoo/odoo8.0-server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/odoo8.0-server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column t0.write_uid does not exist
LINE 2:                 SELECT t0.id AS id,t0.write_uid AS write_uid...

Do i have to make a correction in my module?

Regards

**Comment by astirpe** [comment]
@aldebarande-fr This is an interesting issue. How did you define the model _alde.bilan.geh_? Be sure that the following fields exist in your _alde_bilan_geh_ table:
- write_uid
- write_date
- create_uid
- create_date

**Comment by aldebarande-fr** [comment]
Indeed in my model i didn't have this field because this model is a generate view by a query like this : 

```
def _select(self):
    select_str = """
        SELECT *
            """
    return select_str

def _from(self):
    from_str = """
            *
            """
    return from_str

def _group_by(self):
    group_by_str = """
        group by
            *
            """
    return group_by_str

def init(self, cr):
    tools.drop_view_if_exists(cr, self._table)
    cr.execute("""CREATE or REPLACE VIEW %s as (
        %s
        FROM  (%s)
        %s
        )""" % (self._table, self._select(), self._from(), self._group_by()))
```

I just see the addons didn't see my other custom addons

**Comment by aldebarande-fr** [comment]
I want to know how to create a model recognize by your addons? i think my mistake come from this.
